#+title:         Introducing re-org: tool for generating templates for Org mode
#+date:          2013-12-08
#+layout:        post
#+category:      posts

I have written a small utility named [[https://github.com/wallyqs/re-org][re-org]] that could be useful for
when writing posts in Jekyll.

** Creating a new post with =re-org=

For example, we can create a new Jekyll post like this:

#+begin_src
re-org new jekyll-post --title=sample-post

Created a new writing at `/home/wallyqs/repos/jekyll-org-blog/_drafts/2013-12-08-sample-post.org'
#+end_src

The generated file will include some required attributes to be able to
publish content when using Jekyll.

#+begin_src org
  ,#+title:         Sample post
  ,#+date:          2013-12-08
  ,#+layout:        post
  ,#+category:      posts
#+end_src

By including [[https://gist.github.com/wallyqs/7857206][this plugin]] within the =_plugins= directory from Jekyll, 
we can just use Org mode buffer settings instead of having to add
=YAML= as we are usually supposed to do when using
Jekyll.

~re-org new~ creates the file in the =_drafts= directory, 
so we need to run =jekyll server --drafts= in case we want to see the preview.
For publishing, we just move it to the =_posts= directory, then
~jekyll server~ to render them.

#+begin_src 
mv _drafts/2013-12-08-sample-post.org _posts

jekyll server
#+end_src

** Adding a new template

You can modify the default templates from ~re-org~ by creating a
~_templates~ directory within the Jekyll project. 
The default templates can be inspected like this:

#+begin_src sh
  re-org templates 
  
  - clockfile.org
  - jekyll-post.org
  - notebook.org
  - writing.org
  
  re-org templates --name=jekyll-post.org
  ,#+title:         <%= @org[:title].capitalize.gsub("-", " ") %>
  ,#+date:          <%= @org[:date] %>
  ,#+layout:        post
  ,#+category:      posts
#+end_src

We'll use the contents from the ~jekyll-post.org~ template and create
a new one:

#+begin_src sh
  mkdir _templates
  re-org templates --name=jekyll-post.org > _templates/post.org
  
  re-org templates
  
  ,* Default Templates
  
  - clockfile.org (default)
  - jekyll-post.org       (default)
  - notebook.org  (default)
  - writing.org   (default)
  - post.org      (found at _templates/)
#+end_src

As we can see, ~ERB~ tags can be used to modify the content of the
template that will be used. Having done that, we can use it to setup
the template for the next writing:

#+begin_src sh
  re-org new post --title=getting-started-with-jekyll-and-org-mode
  Created a new writing at `/home/wallyqs/repos/jekyll-org-blog/_drafts/2013-12-08-getting-started-with-jekyll-and-org-mode.org'
  
  
  cat _drafts/2013-12-08-getting-started-with-jekyll-and-org-mode.org
  ,#+title:         Getting started with jekyll and org mode
  ,#+date:          2013-12-08
  ,#+layout:        post
  ,#+category:      posts
#+end_src

I'm satisfied with the current state of the =re-org= utility so I have
released as a gem as well. It definitely needs more polish but the
basic idea is there.

To install:

#+begin_src sh
gem install re-org
#+end_src

If you find this remotely useful, please don't hesitate to submit a
ticket in Github: <https://github.com/wallyqs/re-org/issues>
