# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'ops●tokyo'
tagline:          'a blog by'
description:      '<a href="https://twitter.com/wallyqs" target="_blank">@wallyqs</a>'
baseurl:          /

author:
  name:           '@wallyqs'
  url:            https://twitter.com/wallyqs

paginate:         5
